### ISSUE TITLE
You might want to update sensirion_voc_algorithm.c

### ISSUE THREAD

**Issue by serunis** [adafruit/Adafruit_SGP40#1]
https://github.com/Sensirion/embedded-sgp/releases/tag/7.1.2

You might want to update sensirion_voc_algorithm.c.

It may not be an issue of AVR compiler, but why not?

Sensirion release sgp40_voc_index_arduino-7.1.2.zip on 2021-05-07
They stated "Fix fix16_mul() in voc-algorithm to work properly with 8-bit PIC compilers (and possibly others)"

I updated myself, and it works fine.

Thank you

**Comment by dhalbert** [comment]
We would welcome a pull request. Thanks!
