### ISSUE TITLE
VOC return Zero

### ISSUE THREAD

**Issue by SphaeroX** [adafruit/Adafruit_SGP40#6]
I conencted the SGP40 together with the SHT31 on a ESP32 (Lolin32 Lite). All measurements are OK, only the calculation according to the algorithm does not fit...

Temp -> 21.14
Humi -> 51.82
Raw -> 27737
VOC Index -> 0

**Comment by SphaeroX** [comment]
After some time, the VOC value came on its own, probably had to heat up first?

**Comment by RoyBellingan** [comment]
After how much time did the value of the VOC index started to appear ?

**Comment by ladyada** [comment]
should be after a few seconds
